## Let's tell XChat whta the heck we are
IRC::register("FunFact-script","V1");

## Commands
IRC::add_command_handler ("funfact","funfact");

## Starting..
IRC::print("\002Created by Killerfurbies \(\killerfurbies.kicks-ass.net #KillerNet \)\n");
IRC::print("Useless Facts were provided by http://engr.smu.edu/~rada/UselessFacts.html\n");
IRC::print("	/funfact		- Say a random fun fact\n");

## Listing fun facts
sub funfact {
	## List of fun facts...
	@objects = (
"Fun Fact of the Moment: For every human being on earth, there are about 200 million insects.",
"Fun Fact of the Moment: The harmonica is the world's most popular instrument.",
"Fun Fact of the Moment: By the time they are 65 years old, most Americans have watched more than nine years worth of television.",
"Fun Fact of the Moment: The puck in ice hockey can travel at up to 118 mph (190 km/h).",
"Fun Fact of the Moment: If you stretched all the nerves in the body from end to end, they would be about 47 miles long.",
"Fun Fact of the Moment: Humans have more than 600 muscles in their bodies.",
"Fun Fact of the Moment: Rubber bands last longer when refrigerated.",
"Fun Fact of the Moment: Peanuts are one of the ingredients of dynamite.",
"Fun Fact of the Moment: There are 293 ways to make change for a dollar.",
"Fun Fact of the Moment: The average person's left hand does 56% of the typing.",
"Fun Fact of the Moment: A shark is the only fish that can blink with both eyes.",
"Fun Fact of the Moment: There are more chickens than people in the world.",
"Fun Fact of the Moment: Two-thirds of the world's eggplant is grown in New Jersey.",
"Fun Fact of the Moment: The longest one-syllable word in the English language is 'screeched'.",
"Fun Fact of the Moment: All of the clocks in the movie 'Pulp Fiction' are stuck on 4:20.",
"Fun Fact of the Moment: No word in the English language rhymes with month, orange, silver or purple.",
"Fun Fact of the Moment: 'Dreamt' is the only English word that ends in the letters 'mt'.",
"Fun Fact of the Moment: All 50 states are listed across the top of the Lincoln Memorial on the back of the $5 bill.",
"Fun Fact of the Moment: Almonds are a member of the peach family.",
"Fun Fact of the Moment: Winston Churchill was born in a ladies' room during a dance.",
"Fun Fact of the Moment: Maine is the only state whose name is just one syllable.",
"Fun Fact of the Moment: The largest cabbage weighed 144 lbs.",
"Fun Fact of the Moment: There are only four words in the English language which end in '-dous': tremendous, horrendous, stupendous, and hazardous.",
"Fun Fact of the Moment: Los Angeles's full name is 'El Pueblo de Nuestra Senora la Reina de Los Angeles de Porciuncula' and can be abbreviated to 3.63% of its size: 'L.A'.",
"Fun Fact of the Moment: A cat has 32 muscles in each ear.",
"Fun Fact of the Moment: An ostrich's eye is bigger than its brain.",
"Fun Fact of the Moment: Tigers have striped skin, not just stripped fur.",
"Fun Fact of the Moment: In most advertisements, the time displayed on a watch is 10:10.",
"Fun Fact of the Moment: Al Capone's business card said he was a used furniture dealer.",
"Fun Fact of the Moment: The characters Bert and Ernie on Sesame Street were named after Bert the cop and Ernie the taxi driver in Frank Capra's 'Its A Wonderful Life'.",
"Fun Fact of the Moment: A dragonfly has a life span of 24 hours.",
"Fun Fact of the Moment: A goldfish has a memory span of three seconds.",
"Fun Fact of the Moment: It's impossible to sneeze with your eyes open.", 
"Fun Fact of the Moment: The giant squid has the largest eyes in the world.",
"Fun Fact of the Moment: In England, the Speaker of the House is not allowed to speak.",
"Fun Fact of the Moment: The microwave was invented after a researcher walked by a radar tube and a chocolate bar melted in his pocket.",
"Fun Fact of the Moment: Mr. Rogers is an ordained minister.",
"Fun Fact of the Moment: There are 336 dimples on a regulation golf ball.",
"Fun Fact of the Moment: 'Stewardesses' is the longest word that is typed with only the left hand.",
"Fun Fact of the Moment: Many hamsters blink one eye at a time.",
"Fun Fact of the Moment: The inventor of the flushing toilet was Thomas Crapper.",
"Fun Fact of the Moment: The average bed is home to over 6 billion dust mites.",
"Fun Fact of the Moment: Plastic lawn flamingos outnumber real flamingos in the U.S.A.",
"Fun Fact of the Moment: Whitby, Ontario has more donut stores per capita than any other place in the world.",
"Fun Fact of the Moment: Starfish have no brain.",
"Fun Fact of the Moment: Dolphins sleep with one eye open.",
"Fun Fact of the Moment: Ernest Vincent Wright wrote a novel with over 50,000 words, none of which containing the letter 'E'.",
"Fun Fact of the Moment: Bulls are color blind.",
"Fun Fact of the Moment: A can of SPAM is opened every 4 seconds.",
"Fun Fact of the Moment: 'Babe' was played by over 48 pigs.",
"Fun Fact of the Moment: Mosquitoes have 47 teeth.",
"Fun Fact of the Moment: Lip stick contains fish scales.",
"Fun Fact of the Moment: The Poison Arrow frog has enough poison to kill 2200 people.",
"Fun Fact of the Moment: The largest known kidney stone weighed 1.36 kilograms.",
"Fun Fact of the Moment: Kidney stones come in any color from yellow to brown.",
"Fun Fact of the Moment: Women blink twice as many times as men do.",
"Fun Fact of the Moment: The McDonalds at the SkyDome in Toronto, Ontario is the only one in the world that sells hot dogs.",
"Fun Fact of the Moment: A bowling pin only has to tilt 7.5 degrees in order to fall down.",
"Fun Fact of the Moment: The first episode of Leave It To Beaver aired on October 4, 1957.",
"Fun Fact of the Moment: Beaver Cleaver's locker number is 9.",
"Fun Fact of the Moment: The first flushing toilet seen on TV was on Leave It To Beaver.",
"Fun Fact of the Moment: Jerry Seinfeld's apartment number (on the show) is 5A. In the old episodes it was 3A.",
"Fun Fact of the Moment: The life span of a taste bud is ten days.",
"Fun Fact of the Moment: Pi has been calculated to 2,260,321,363 digits.",
"Fun Fact of the Moment: The billionth digit in Pi is 9.",
"Fun Fact of the Moment: The first 100 numbers of Pi are: 
3.14159265358979323846264338327950288419716939937510 
58209749445923078164062862089986280348253421170679.",
"Fun Fact of the Moment: A stretched out Slinky is 87 feet long.",
"Fun Fact of the Moment: An iguana can stay under water for 28 minutes.",
"Fun Fact of the Moment: Emus can't walk backwards.",
"Fun Fact of the Moment: A group of unicorns is called a blessing.",
"Fun Fact of the Moment: A group of kangaroos is called a mob.",
"Fun Fact of the Moment: A group of whales is called a pod.",
"Fun Fact of the Moment: A group of geese is called a gaggle.",
"Fun Fact of the Moment: A group of owls is called a parliament.",
"Fun Fact of the Moment: A group of ravens is called a murder.",
"Fun Fact of the Moment: A group of bears is called a sleuth.",
"Fun Fact of the Moment: 12 or more cows is called a flink.",
"Fun Fact of the Moment: A baby oyster is called a spat.",
"Fun Fact of the Moment: Chickens can't swallow while they are upside down.",
"Fun Fact of the Moment: In the October 22, 1945 edition of Life magazine there was a picture of a chicken with its head cut off. It was alive too!",
"Fun Fact of the Moment: The average garden variety caterpillar has 248 muscles in its head.",
"Fun Fact of the Moment: Pinocchio was made of pine.",
"Fun Fact of the Moment: The largest pumpkin weighed 377 lbs.",
"Fun Fact of the Moment: A mule won't sink in quicksand but a donkey will.",
"Fun Fact of the Moment: More people are killed annually by donkeys than in airplane crashes.",
"Fun Fact of the Moment: Alfred Hitchcock had no belly button for it was eliminated during surgery.",
"Fun Fact of the Moment: There are 22 stars in the Paramount logo.",
"Fun Fact of the Moment: The average human produces 10,000 gallons of saliva in a lifetime.",
"Fun Fact of the Moment: A quarter has 119 grooves around the edge.",
"Fun Fact of the Moment: A dime has 118 ridges around the edge.",
"Fun Fact of the Moment: Cranberry Jell-0 is the only kind that contains real fruit.",
"Fun Fact of the Moment: The plastic things on the end of shoelaces are called aglets.",
"Fun Fact of the Moment: Every time you lick a stamp you consume 1/10 of a calorie.",
"Fun Fact of the Moment: The pound sign # is called anoctothorpe.",
"Fun Fact of the Moment: Maine is the toothpick capital of the world.",
"Fun Fact of the Moment: New Jersey has a spoon museum with over 5,400 spoons from almost all the states.",
"Fun Fact of the Moment: There was once a town in West Virginia called '6'.",
"Fun Fact of the Moment: Singapore only has one train station.",
"Fun Fact of the Moment: The parking meter was invented in North Dakota.",
"Fun Fact of the Moment: Napolean made his battle plans in a sandbox.",
"Fun Fact of the Moment: Roman Emperor Caligula made his horse a senator.",
"Fun Fact of the Moment: The green stuff on the occasional freak potatoe chip is chlorophyll.",
"Fun Fact of the Moment: If you ate too many carrots you would turn orange.",
"Fun Fact of the Moment: Pluto's orbit crosses Neptune's making Pluto the eighth planet from the sun. It has been that way since 1979 and will remain that way until 1999.",
"Fun Fact of the Moment: The earth is approx. 6,588,000,000,000,000,000 tons.",
"Fun Fact of the Moment: The force of 1 billion people jumping at the same time is equal to 500 tons of TNT.",
"Fun Fact of the Moment: Popeye was 5'6'.",
"Fun Fact of the Moment: Howdy Doody had 48 freckles.",
"Fun Fact of the Moment: The first word spoken on the moon was 'Okay'.",
"Fun Fact of the Moment: Neil Armstrong stepped on the moon with his left foot first.",
"Fun Fact of the Moment: The average speed of Heinz ketchup leaving the bottle is 25 miles per year.",
"Fun Fact of the Moment: Hilary Clinton once said We are the President.",
"Fun Fact of the Moment: The percent of women who wash their hands after leaving a restroom is 80%.",
"Fun Fact of the Moment: The percent of men who wash their hands after using a restroom is 55%.",
"Fun Fact of the Moment: There are 333 toilet paper squares on a toilet paper roll.",
"Fun Fact of the Moment: The Eifel Tower has 2,500,000 rivets in it.",
"Fun Fact of the Moment: 'Jaws' is the most common name for a goldfish.",
"Fun Fact of the Moment: On an average work day, a typist's fingers travel 12.6 miles.",
"Fun Fact of the Moment: The average American eats 2 donuts a day.",
"Fun Fact of the Moment: The longest word in the Old Testament is Malhershalahashbaz.",
"Fun Fact of the Moment: The longest time a person has been in a coma is 37 years.",
"Fun Fact of the Moment: Every minute in the U.S 6 people turn 17.",
"Fun Fact of the Moment: It takes the Where's Waldo artist one month to complete a drawing.",
"Fun Fact of the Moment: 2500 lefties die each year using products designed for righties.",
"Fun Fact of the Moment: A baby is born every 7 seconds.",
"Fun Fact of the Moment: 10 tons of space dust fall on the Earth everyday.",
"Fun Fact of the Moment: On average, a 4 year old child asks 437 questions a day.",
"Fun Fact of the Moment: Blue and white are the most common school colors.",
"Fun Fact of the Moment: Swimming pools in Phoenix, Arizona, pick up 20 pounds of dust a year.",
"Fun Fact of the Moment: The first message tapped by Samuel Morse over his invention the telegraph was: What hath God wrought?.",
"Fun Fact of the Moment: The first words spoken by over Alexander Bell over the telephone were: Watson, please come here. I want you.",
"Fun Fact of the Moment: The first words spoken by Thomas Edison over the phonograph were: Mary had a little lamb.",
"Fun Fact of the Moment: The three words in the English language with the letters uu are: vacuum, residuum and continuum.",
"Fun Fact of the Moment: A baby in Florida was named: Truewilllaughinglifebuckyboomermanifestdestiny. His middle name is George James.",
"Fun Fact of the Moment: It is illegal to ride a street car on Sunday if have been eating garlic in Toronto, Ontario, Canada.",
"Fun Fact of the Moment: In a normal life time an American will eat 200 pounds of peanuts and 10,000 pounds of meat.",
"Fun Fact of the Moment: A new book is published every 13 minutes in America.",
"Fun Fact of the Moment: America's best selling ice-cream flavour is vanilla.",
"Fun Fact of the Moment: American's eat 18 billion hot dogs a year.",
"Fun Fact of the Moment: American's eat 134 pounds of sugar a year.",
"Fun Fact of the Moment: Every year the sun loses 360 million tons.",
"Fun Fact of the Moment: Because of Animal Crackers, many kids until they reach the age of ten, believe a bear is as tall as a giraffe.",
"Fun Fact of the Moment: You can tell if a skunk is about if you smell only .000 000 000 000 071 ounce of its spray.",
"Fun Fact of the Moment: Animal breeders in Russia once claimed to have bred sheep with blue wool.",
"Fun Fact of the Moment: Penguins are the only bird that can leap into the air like porpoises.",
"Fun Fact of the Moment: India has 50 million monkeys.",
"Fun Fact of the Moment: By some unknown means, an iguana can end its own life.",
"Fun Fact of the Moment: Americans spend around $3 billion for cat and dog food a year.",
"Fun Fact of the Moment: Pigs can cover a mile in 7.5 minutes when running at top speed.",
"Fun Fact of the Moment: You breathe about 10 million times a year.",
"Fun Fact of the Moment: The colder the room you sleep in, the better the chances are that you'll have a bad dream.",
"Fun Fact of the Moment: The first non-human to win an Oscar was Mickey Mouse.",
"Fun Fact of the Moment: Lee Harvey Oswald was booked with mugshot number 54018.",
"Fun Fact of the Moment: The Gulf Stream could carry a message in a bottle at an average of 4 miles per hour.",
"Fun Fact of the Moment: The bullseye on a dartboard must be 5 feet 8 inches off the ground.",
"Fun Fact of the Moment: The foot is the most common body part bitten by insects.",
"Fun Fact of the Moment: The most common time for a wake up call is 7am.",
"Fun Fact of the Moment: The doorbell was invented in 1831.",
"Fun Fact of the Moment: The are 255 squares on a Scrabble board.",
"Fun Fact of the Moment: The electric shaver was patented on November 6, 1928.",
"Fun Fact of the Moment: There are 500 sheets of paper in a ream.",
"Fun Fact of the Moment: The monkey wrench was invented by Charles Moncke.",
"Fun Fact of the Moment: Japan is the largest exporter of frog's legs.",
"Fun Fact of the Moment: There are seven points on the Statue of Liberty's crown.",
"Fun Fact of the Moment: There are approx. 550 hairs in the eyebrow.",
"Fun Fact of the Moment: The most common non-contagious disease in the world is tooth decay.",
"Fun Fact of the Moment: The shell constitutes 12 percent of an egg's weight.",
"Fun Fact of the Moment: A squid has 10 tentacles.",
"Fun Fact of the Moment: A snail's reproductive organs are in its head.",
"Fun Fact of the Moment: A cow's only sweat glands are in its nose.",
"Fun Fact of the Moment: The word 'AND' appears 46,277 times in the Bible.",
"Fun Fact of the Moment: The first word played in the Scrabble rules demonstration game is 'horn'.",
"Fun Fact of the Moment: The telephone's U.S. patent number is 174,465.",
"Fun Fact of the Moment: The typical person goes to the bathroom 6 times a day.",
"Fun Fact of the Moment: There are 17 steps leading up to Sherlock Holme's apartment.",
"Fun Fact of the Moment: When a horned toad is angry, it squirts blood from it's eyes.",
"Fun Fact of the Moment: Napoleon was terrified of cats.",
"Fun Fact of the Moment: The first Lifesaver flavor was peppermint.",
"Fun Fact of the Moment: The typical American eats 263 eggs a year.",
"Fun Fact of the Moment: The ballpoint pen was invented in 1938 by Laszlo and Georg Biro.",
"Fun Fact of the Moment: The fastest growing nail is on the middle finger.",
"Fun Fact of the Moment: The parking meter was invented by C C Magee in 1935.",
"Fun Fact of the Moment: In 1961, an IBM 7090 computer calculated Pi to 100 265 digits.",
"Fun Fact of the Moment: The human body weighs forty times more than the brain.",
"Fun Fact of the Moment: After eating too much, your hearing is less sharp.",
"Fun Fact of the Moment: A person swallows approximately 295 times while eating dinner.",
"Fun Fact of the Moment: The oldest known vegetable is the pea.",
"Fun Fact of the Moment: Jack is the most common name in nursery rhymes.",
"Fun Fact of the Moment: The avocado has the most calories of any fruit.",
"Fun Fact of the Moment: The first zoo in the USA was in Philadelphia.",
"Fun Fact of the Moment: The letter N ends all Japanese words not ending in a vowel.",
"Fun Fact of the Moment: France has the highest per capita consumption of cheese.",
"Fun Fact of the Moment: The hardest bone in the human body is the jawbone.",
"Fun Fact of the Moment: 4000 people are injured by teapots each year.",
"Fun Fact of the Moment: The typical American consumes 27 pounds of cheese each year.",
"Fun Fact of the Moment: The shortest English word that contains the letters A, B, C, D, E, and F is feedback.",
"Fun Fact of the Moment: The ostrich has a 46 foot long small intestine.",
"Fun Fact of the Moment: The state of California raises the most turkeys out of all of the states.",
"Fun Fact of the Moment: The most sensitive finger on the human hand is the index finger.",
"Fun Fact of the Moment: George Washington Carver invented peanut butter.",
"Fun Fact of the Moment: The typical hen lays 19 dozen eggs a year.",
"Fun Fact of the Moment: Stainless stell was invented by Harry Brearley in 1913.",
"Fun Fact of the Moment: A scallop has 35 blue eyes.",
"Fun Fact of the Moment: The left leg of a chicken in more tender than the right one.",
"Fun Fact of the Moment: The only dog that doesn't have a pink tongue is the chow.",
"Fun Fact of the Moment: Iceland was the first country to legalize abortion in 1935.",
"Fun Fact of the Moment: The giraffe has the highest blood pressure of any animal.",
"Fun Fact of the Moment: The dumbest domesticated animal is the turkey.",
"Fun Fact of the Moment: Russia has the most movie theaters in the world.",
"Fun Fact of the Moment: Albert Blake Dick invented the mimeograph machine.",
"Fun Fact of the Moment: The strongest muscle in the human body is the tongue.",
"Fun Fact of the Moment: The most fatal car accidents occur on Saturday.",
"Fun Fact of the Moment: An Oscar weighs seven pounds.",
"Fun Fact of the Moment: It takes the typical person seven minutes to fall asleep.",
"Fun Fact of the Moment: Gabriel Fahrenheit invented the mercury thermometer.",
"Fun Fact of the Moment: The Eiffel Tower has 1792 steps.",
"Fun Fact of the Moment: The mongoose was barred live entry into the U.S. in 1902.",
"Fun Fact of the Moment: Ants stretch when they wake up in the morning.",
"Fun Fact of the Moment: Thomas Edison, lightbulb inventor, was afraid of the dark.",
"Fun Fact of the Moment: About 3000 years ago, most Egyptians died by the time they were 30.",
"Fun Fact of the Moment: A sneeze travels out your mouth at over 600 m.p.h.",
"Fun Fact of the Moment: The average person has over 1,460 dreams a year.",
"Fun Fact of the Moment: Lightning strikes about 6,000 times per minute on this planet.",
"Fun Fact of the Moment: Owls are the only birds who can see the color blue.",
"Fun Fact of the Moment: A jellyfish is 95 percent water.",
"Fun Fact of the Moment: The elephant is the only mammal that can't jump.",
"Fun Fact of the Moment: The penguin is the only bird who can swim, but not fly.",
"Fun Fact of the Moment: America once issued a 5-cent bill.",
"Fun Fact of the Moment: Like fingerprints, everyone's tongue print is different.",
"Fun Fact of the Moment: Fortune cookies were actually invented in America, in 1918, by Charles Jung.",
"Fun Fact of the Moment: A giraffe can clean its ears with its 21-inch tongue.",
"Fun Fact of the Moment: Chewing gum while peeling onions will keep you from crying.",
"Fun Fact of the Moment: Bats always turn left when exiting a cave.",
"Fun Fact of the Moment: Fingernails grow nearly 4 times faster than toenails.",
"Fun Fact of the Moment: You blink about 84,000,000 times a year.",
"Fun Fact of the Moment: In England, in the 1880's, 'Pants' was considered a dirty word.",
"Fun Fact of the Moment: A toothpick is the object most often choked on by Americans.",
"Fun Fact of the Moment: Every 45 seconds, a house catches on fire in the United States.",
"Fun Fact of the Moment: The sun is 330,330 times larger than the earth.",
"Fun Fact of the Moment: A hummingbird weighs less than a penny.",
"Fun Fact of the Moment: A cockroach will live nine days without it's head, before it starves to death.",
"Fun Fact of the Moment: The most used letter in the English alphabet is 'E', and 'Q' is the least used.",
"Fun Fact of the Moment: Dogs and cats, like humans, are either right of left handed... or is that pawed?",
"Fun Fact of the Moment: The opposite sides of a dice cube always add up to seven.",
"Fun Fact of the Moment: Men are 6 times more likely to be struck by lighting than women.",
"Fun Fact of the Moment: Of all the words in the English language, the word set has the most definitions.",
"Fun Fact of the Moment: Bulls are colorblind, therefore will usually charge at a matador's waving cape no matter what color it is: - be it red or neon yellow.",
"Fun Fact of the Moment: Apples are more efficient than caffeine in keeping people awake in the mornings.",
"Fun Fact of the Moment: Smelling bananas and/or green apples (smelling, not eating) can help you lose weight.",
"Fun Fact of the Moment: After eating, a housefly regurgitates its food and then eats it again!",
"Fun Fact of the Moment: When someone annoys you, it takes 42 muscles to frown, but it only takes 4 muscles to extend your arm and whack them in the head.",
"Fun Fact of the Moment: Coca-Cola was originally green.",
"Fun Fact of the Moment: Hong Kong has the most Rolls Royce's per capita.",
"Fun Fact of the Moment: Alaska is the state with highest percent of people who walk to work.",
"Fun Fact of the Moment: 28 percent of Africa is wilderness.",
"Fun Fact of the Moment: 38 percent of America is wilderness.",
"Fun Fact of the Moment: A duck's quack does not echo and no one knows why.",
"Fun Fact of the Moment: It costs $6400 to raise a medium size dog to age of 11.",
"Fun Fact of the Moment: Average number of people airborne over the U.S. during any given hour: 61,000.",
"Fun Fact of the Moment: 70 percent of Americans who visited Disneyland/World.",
"Fun Fact of the Moment: Intelligent people have more copper and zinc in their hair.",
"Fun Fact of the Moment: The youngest pope was 11 years old.",
"Fun Fact of the Moment: Iceland consumes more Coca-Cola per capita than any other country.",
"Fun Fact of the Moment: The sentence 'The quick brown fox jumps over the lazy dog.' uses every letter in the alphabet and was developed by Western Union to test telex/twx communications.",
"Fun Fact of the Moment: Average life span of a major league baseball: 7 pitches.",
"Fun Fact of the Moment: The San Francisco Cable cars are the only 'mobile' National Monuments.",
"Fun Fact of the Moment: The only 15-letter word that can be spelled without repeating a letter 'uncopyrightable'.",
"Fun Fact of the Moment: The reason firehouses have circular stairways is from the days of yore when the engines were pulled by horses. The horses were stabled on the ground floor and learned how to walk up standard staircases.",
"Fun Fact of the Moment: When opossums are playing 'possum, they are not 'playing.' They actually pass out from sheer terror.",
"Fun Fact of the Moment: The Main Library at Indiana University sinks over an inch every year because, when it was built, engineers failed to take into account the weight of all the books that would occupy the building.",
"Fun Fact of the Moment: Clans of long ago that wanted to get rid of unwanted people (without killing them) used to burn their houses down:  hence the expression 'to get fired'.",
"Fun Fact of the Moment: The longest recorded flight of a chicken is thirteen seconds.",
"Fun Fact of the Moment: David Prowse was the guy in the Darth Vader suit in Star Wars. He spoke all of Vader's lines, and didn't know his voice was going to be dubbed over by James Earl Jones until he saw the screening of the movie.",
"Fun Fact of the Moment: The Pentagon, in Arlington, Virginia, has twice as many bathrooms as is necessary. When it was built in the 1940s, the state of Virginia still had segregation laws requiring separate toilet facilities for blacks and whites.",
"Fun Fact of the Moment: The cruise liner, Queen Elizabeth II, moves only six inches for each gallon of diesel fuel that it burns.",
"Fun Fact of the Moment: The highest point in Pennsylvania is lower than the lowest point in Colorado.",
"Fun Fact of the Moment: Nutmeg is extremely poisonous if injected intravenously.",
"Fun Fact of the Moment: If you have three quarters, four dimes, and four pennies, you have $1.19. You also have the largest amount of money in coins without being able to make change for a dollar.",
"Fun Fact of the Moment: No NFL team which plays its home games in a domed stadium has ever won a Superbowl.",
"Fun Fact of the Moment: The only two days of the year in which there are no professional sports games (MLB, NBA, NHL, or NFL) are the day before and the day after the Major League All-star Game.",
"Fun Fact of the Moment: Only one person in two billion will live to be 116 or older.",
"Fun Fact of the Moment: Pound for pound, hamburgers cost more than new cars.",
"Fun Fact of the Moment: The 3 most valuable brand names on earth: Marlboro, Coca-Cola, and Budweiser, in that order.",
"Fun Fact of the Moment: It's possible to lead a cow upstairs...but not downstairs.",
"Fun Fact of the Moment: Ninety percent of New York City cabbies are recently arrived immigrants.",
"Fun Fact of the Moment: In 10 minutes, a hurricane releases more energy than all the world's nuclear weapons combined.",
"Fun Fact of the Moment: Reno, Nevada is west of Los Angeles, California.",
"Fun Fact of the Moment: The cigarette lighter was invented before the match.",
"Fun Fact of the Moment: If you yelled for 8 years, 7 months and 6 days, you would have produced enough sound energy to heat one cup of coffee.",
"Fun Fact of the Moment: The human heart creates enough pressure when it pumps out to the body to squirt blood 30 feet.",
"Fun Fact of the Moment: Banging your head against a wall uses 150 calories an hour.",
"Fun Fact of the Moment: On average people fear spiders more than they do death.",
"Fun Fact of the Moment: You can't kill yourself by holding your breath.",
"Fun Fact of the Moment: You are more likely to be killed by a champagne cork than by a poisonous spider.",
"Fun Fact of the Moment: Right-handed people live, on average, nine years longer than left-handed people do.",
"Fun Fact of the Moment: In ancient Egypt, Priests plucked every hair from their bodies, including their eyebrows and eyelashes.",
"Fun Fact of the Moment: A crocodile cannot stick its tongue out.",
"Fun Fact of the Moment: Butterflies taste with their feet.",
"Fun Fact of the Moment: A cat's urine glows under a blacklight.",
"Fun Fact of the Moment: The first couple to be shown in bed together on prime time television were Fred and Wilma Flintstone.",
"Fun Fact of the Moment: Coca Cola was originally green.",
"Fun Fact of the Moment: The Ten Commandments contain 297 words.",
"Fun Fact of the Moment: The Bill of Rights is stated in 463 words.",
"Fun Fact of the Moment: Lincoln's Gettysburg Address contains 266 words.",
"Fun Fact of the Moment: A recent federal directive to regulate the price of cabbage contains 26,911 words.",
"Fun Fact of the Moment: There are more collect calls made on Father's Day than on any other day.",
"Fun Fact of the Moment: Every day more money is printed for monopoly than the US Treasury.",
"Fun Fact of the Moment: Men can read smaller print than women, women can hear better than men.",
"Fun Fact of the Moment: Barbie's measurements if she were life size: 39-23-33.",
"Fun Fact of the Moment: The world's youngest parents were 8 & 9 and lived in China in 1910.",
"Fun Fact of the Moment: Honey is the only food that doesn't spoil.",
"Fun Fact of the Moment: Half of all Americans live within 50 miles of their birthplace.",
"Fun Fact of the Moment: The youngest Pope was 11 years old.",
"Fun Fact of the Moment: 'I am.' is the shortest complete sentence in the English language.",
"Fun Fact of the Moment: The nursery rhyme Ring Around the Rosey is a rhyme about the bubonic plague. Infected people with the plague would get red circular sores (Ring around the Rosey...). These sores would smell very bad so people would hide flowers on their bodies in an attempt to mask the smell ('pocket full of posies...'). People who died from the plague would be burned to reduce the spread of the disease ('ashes, ashes, we all fall down').",
"Fun Fact of the Moment: The citrus soda 7-UP was created in 1929; '7' was selected because the original containers were 7 ounces. 'UP' indicated the direction of the bubbles.",
"Fun Fact of the Moment: Mosquito repellents don't repel. They hide you. The spray blocks the mosquito's sensors so they don't know you're there.",
"Fun Fact of the Moment: Dentists have recommended that a toothbrush be kept at least 6 feet away from a toilet to avoid airborne particles resulting from the flush.",
"Fun Fact of the Moment: The liquid inside young coconuts can be used as substitute for blood plasma.",
"Fun Fact of the Moment: American car horns beep in the tone of F.",
"Fun Fact of the Moment: No piece of paper can be folded more than 7 times.",
"Fun Fact of the Moment: 1 in every 4 Americans has appeared on television.",
"Fun Fact of the Moment: You burn more calories sleeping than you do watching television.",
"Fun Fact of the Moment: Oak trees do not produce acorns until they are fifty years of age or older.",
"Fun Fact of the Moment: The first product to have a bar code was Wrigley's gum.",
"Fun Fact of the Moment: The king of hearts is the only king without a mustache.",
"Fun Fact of the Moment: A Boeing 747s wingspan is longer than the Wright brother's first flight.",
"Fun Fact of the Moment: American Airlines saved $40,000 in 1987 by eliminating 1 olive from each salad served in first-class.",
"Fun Fact of the Moment: Venus is the only planet that rotates clockwise.",
"Fun Fact of the Moment: The first CD pressed in the US was Bruce Springsteen's 'Born in the USA'.",
"Fun Fact of the Moment: The 57 on the Heinz ketchup bottle represents the number of varieties of pickles the company once had.",
"Fun Fact of the Moment: Most dust particles in your house are made from dead skin."
);
my $obj = $objects[int(rand($#objects+1))];
IRC::command("$obj");
return 1;
}

